<?php

declare(strict_types=1);

/**
 * phpunit-skeleton-generator
 *
 * Copyright (c) 2012-2014, Sebastian Bergmann <sebastian@phpunit.de>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright
 *  notice, this list of conditions and the following disclaimer in
 *  the documentation and/or other materials provided with the
 *  distribution.
 *
 *  Neither the name of Sebastian Bergmann nor the names of his
 *  contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *  *
 * @author    Sebastian Bergmann <sebastian@phpunit.de>
 * @copyright 2012-2014 Sebastian Bergmann <sebastian@phpunit.de>
 * @license   http://www.opensource.org/licenses/BSD-3-Clause  The BSD 3-Clause License
 * @since     File available since Release 2.0.0
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on %s at %s.
 */
class Calculator2Test extends PHPUnit\Framework\TestCase
{
    protected Calculator2 $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Calculator2();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Generated from @assert(0, 0) == 0.
     *
     * @covers \Calculator2::add
     */
    public function testAdd(): void
    {
        $this->assertEquals(
            0,
            $this->object->add(0, 0),
        );
    }

    /**
     * Generated from @assert(0, 1) == 1.
     *
     * @covers \Calculator2::add
     */
    public function testAdd2(): void
    {
        $this->assertEquals(
            1,
            $this->object->add(0, 1),
        );
    }

    /**
     * Generated from @assert(1, 0) == 1.
     *
     * @covers \Calculator2::add
     */
    public function testAdd3(): void
    {
        $this->assertEquals(
            1,
            $this->object->add(1, 0),
        );
    }

    /**
     * Generated from @assert(1, 1) == 2.
     *
     * @covers \Calculator2::add
     */
    public function testAdd4(): void
    {
        $this->assertEquals(
            2,
            $this->object->add(1, 1),
        );
    }
}
